/* SPDX-License-Identifier: GPL-2.0-or-later
 * digimachine (Core A): the wavetable machine's main-CPU side.
 * Digitone mk1 / Keys, OS 1.43.
 *
 * The machine's audio is rendered on the second CPU (Core B) into a reserved
 * shared-RAM slot (+0x880: 32 stereo frames). This mod:
 *   1. uploads the fixed wavetable set to shared RAM (+0x1000) once, at boot;
 *   2. writes the machine's parameters to shared RAM (+0x800) each block;
 *   3. returns the machine audio into the mix, with level/pan and the three
 *      main-FX sends (delay/reverb/od) on the AMP page.
 *
 * Phase 1a returns through the master insert (ev_render_out), the proven
 * combinable path. Phase 1b moves the return to the voice-mix/send stage so
 * the stock DELAY/REVERB/OVERDRIVE chains process it.
 *
 * Shared RAM (main CPU base 0x10000000):
 *   +0x800 params   (main -> DSP)   see DM_P_*
 *   +0x840 state    (DSP -> main)   env/level, for the page animation
 *   +0x880 audio    (DSP -> main)   32 x {int32 L, int32 R}
 *   +0x1000 tables  (main -> DSP)   8 x 256 x int16
 */
#include "../../src/corea.h"

#define DM_SHARED   0x10000000u
#define DM_PARAMS   (DM_SHARED + 0x800u)
#define DM_STATE    (DM_SHARED + 0x840u)
#define DM_AUDIO    (DM_SHARED + 0x880u)
#define DM_TABLES   (DM_SHARED + 0x1000u)
#define DM_CODE     (DM_SHARED + 0x8000u)     /* Core B engine image */
#define DM_MAGIC    (DM_SHARED + 0x7fcu)      /* "DMAC": upload-complete flag */
#define DM_MAGIC_V  0x444d4143u

/* exported parameters (the page edits these) */
int dmachine_on = 0;            /* off until a MIDI track selects the machine */
int dmachine_inc = 39300000;    /* phase increment: ~440 Hz at 48 kHz (2^32/cycle) */
int dmachine_detune = 0;        /* Q14 detune delta */
int dmachine_width = 0;         /* 0..16384: phase offset between readers */
int dmachine_morph = 0;         /* 0..7<<8 table position */
int dmachine_level = 16384;     /* Q15 output gain */
int dmachine_pan = 0;           /* -8192..8191 Q14 */
int dmachine_send_delay = 0;    /* Q15 */
int dmachine_send_reverb = 0;   /* Q15 */
int dmachine_send_od = 0;       /* Q15 */
/* filter (FILT page) */
int dmachine_filt_type = 0;     /* 0=LP 1=HP 2=BP 3=OFF */
int dmachine_filt_freq = 96;    /* 0..127 */
int dmachine_filt_reso = 4;     /* 0..15 */
int dmachine_filt_env = 0;      /* env depth (Q14, reserved) */
/* amp envelope (AMP page), all in per-block ticks of the ramp */
int dmachine_amp_a = 4;         /* attack  */
int dmachine_amp_d = 8;         /* decay   */
int dmachine_amp_s = 16384;     /* sustain (Q15) */
int dmachine_amp_r = 8;         /* release */
int dmachine_gate = 1;          /* note gate; 1 until the note path drives it */

/* 8 single-cycle tables, 256 samples, int16, normalised.
 * sine/tri/saw/square/pulse25/organ/formant/metallic. Generated below. */
static const short dm_table[8][256] = {
#include "tables.inc"
};

/* the Core B engine image, uploaded to shared RAM (the cave trampoline jumps
 * here). Generated by tools/build_dsp.py -> dsp/engine.bin -> this include. */
static const unsigned char dm_engine[] = {
#include "engine_blob.inc"
};

void dmachine_boot(void)
{
    volatile short *t = (volatile short *)DM_TABLES;
    volatile unsigned char *c = (volatile unsigned char *)DM_CODE;
    int i, j;
    for (i = 0; i < 8; i++)
        for (j = 0; j < 256; j++)
            t[i * 256 + j] = dm_table[i][j];
    for (i = 0; i < (int)sizeof(dm_engine); i++)
        c[i] = dm_engine[i];
    /* Last: the engine checks this before it will run. Writes are ordered
     * against the copies above by the compiler, but mark it volatile so it
     * cannot be reordered or elided. */
    *(volatile unsigned *)DM_MAGIC = DM_MAGIC_V;
}

/* One-shot upload, run at the first UI tick (30 Hz) and again at the first
 * render entry, whichever comes first. Core B's cave trampoline jumps into
 * shared +0x8000 on its first render, so the engine and tables must be there
 * before that; without this the machine was dead code and Core B executed
 * uninitialised shared RAM (access violation). The ev_tick handler is the
 * primary trigger (it fires before the OS is fully up); the render_in guard
 * closes the remaining race for a snapshot resumed straight into audio. */
static int dm_booted = 0;

void dmachine_ensure_boot(void)
{
    if (!dm_booted) {
        dmachine_boot();
        dm_booted = 1;
    }
}

void dmachine_tick(void *ctrl)
{
    (void)ctrl;
    dmachine_ensure_boot();
}

/* transport state (prof.transport_state): the machine's gate follows it, so the
 * machine plays while the sequencer runs. Note-by-note pitch is a later pass. */
#define DM_TRANSPORT 0x4138E208u

/* The currently selected track's sound base (prof.pattern_ptr / the pointer the
 * algorithm getter 0x4009444a reads). Its ALGORITHM is the long at +0x16119 -
 * the getter reads exactly this, so the read is aligned in practice (the stock
 * OS itself does a `movel` through it). We engage the machine whenever that
 * algorithm is one of the added slots (>= 8), i.e. when the SYN1 page is set to
 * WAVETABLE. This is what turns dmachine_on on in the pivot: with no machine UX,
 * selecting a wavetable slot is the whole interface. */
#define DM_SOUND_PTR 0x4138E214u
#define DM_ALGO_OFF  0x16119u
#define DM_ALGO_MIN  8

static int dm_algo(void)
{
    unsigned base = *(volatile unsigned *)DM_SOUND_PTR;
    if (!base)
        return 0;
    return (int)*(volatile int *)(base + DM_ALGO_OFF);
}

static void dm_push_params(void)
{
    volatile int *p = (volatile int *)DM_PARAMS;
    int gate = *(volatile unsigned *)DM_TRANSPORT ? 1 : dmachine_gate;
    p[0] = dmachine_on;                       /* P_ON */
    p[1] = dmachine_inc;                      /* P_TUNE (increment) */
    p[2] = dmachine_detune;                   /* P_DETUNE */
    p[3] = dmachine_width;                    /* P_WIDTH */
    p[4] = dmachine_morph;                    /* P_MORPH */
    p[5] = dmachine_level;                    /* P_AMP/LEVEL */
    p[6] = dmachine_pan;                      /* P_PAN */
    p[7] = dmachine_filt_type;                /* P_FTYPE */
    p[8] = dmachine_filt_freq;                /* P_FFREQ */
    p[9] = dmachine_filt_reso;                /* P_FRESO */
    p[10] = dmachine_filt_env;                /* P_FENV */
    p[11] = dmachine_amp_a;                   /* P_ATTACK */
    p[12] = dmachine_amp_d;                   /* P_DECAY */
    p[13] = dmachine_amp_s;                   /* P_SUSTAIN */
    p[14] = dmachine_amp_r;                   /* P_RELEASE */
    p[15] = gate;                             /* P_GATE */
}

void dmachine_render_in(void)
{
    /* Upload the engine/tables before Core B can reach them (first render). */
    dmachine_ensure_boot();
    /* Engage the machine while the selected track's SYN1 algorithm is a
     * wavetable slot (>= 8). The Core A program only widened the descriptor and
     * setter (mod.json); this is the consumer side. */
    dmachine_on = dm_algo() >= DM_ALGO_MIN ? 1 : 0;
    dm_push_params();
}

/* the send-stage source bus: the voice mix writes it, then each stock send
 * copies it into its FX input bus. Adding the machine here (before the sends)
 * means the stock DELAY/REVERB/OVERDRIVE chains process it. */
#define DM_SRC_BUS  0x8000EF70u

/* Replaces the send call at 0x400971e6 (jsr 0x4009a16a): add the machine audio
 * into the source bus, then run the stock send. The machine then flows through
 * the stock FX and master exactly like a voice (no separate dry insert). */
void dmachine_bus_tap(void)
{
    void (*stock_send)(void) = (void (*)(void))0x4009A16A;
    volatile int *m = (volatile int *)DM_AUDIO;
    volatile int *b = (volatile int *)DM_SRC_BUS;
    int i, lvl = dmachine_level, sends;
    if (dmachine_on) {
        sends = dmachine_send_delay + dmachine_send_reverb + dmachine_send_od;
        sends = sends < 0 ? 0 : sends > 32767 ? 32767 : sends;
        for (i = 0; i < DN_OUT_FRAMES; i++) {
            int ml = dn_q15(m[0], lvl);
            int mr = dn_q15(m[1], lvl);
            int stl = dn_q15(ml, sends), str = dn_q15(mr, sends);
            b[0] += ml + stl;
            b[1] += mr + str;
            b += 2;
            m += 2;
        }
    }
    stock_send();
}

/* The dry return is the bus tap above; this stays a no-op so the subscription
 * in mod.json is harmless and the mod still combines. */
void dmachine_render_out(void)
{
}
