# SPDX-License-Identifier: GPL-2.0-or-later
"""Build the digimachine Core B (second-CPU) blob and its .dspmod.json.

Core B has no linker and no loader: elekloader.dsp applies whole-instruction
sites with ABSOLUTE targets to section 7. So this tool:

  1. assembles dsp/engine.s at a fixed VMA (--vma),
  2. objcopy -O binary -> the raw engine image,
  3. reads the stock section 7 to take the exact `stock` bytes for:
       - the hook site (a `jsr` at --hook in the render), and
       - the code blob placed at --vma,
  4. writes dsp/digimachine.dspmod.json.

usage:
    python tools/build_dsp.py [--hook 0x40000A0A] [--vma 0x4001F048]
                              [--stock <syx>] [--out dsp/digimachine.dspmod.json]
"""
import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.dirname(HERE)
DSP = os.path.join(MOD, "dsp")

STOCK_DEFAULT = r"C:\Users\benan\Music\ELEKTRON\Digitone_and_Digitone_Keys_OS1.43.syx"
CROSS = os.environ.get("ELEKLOADER_CROSS", "m68k-elf-")
SECTION7_LOAD = 0x40000400
HOOK_DEFAULT = 0x40000A0A          # jsr 0x40003848 (output copy)
TRAMP_DEFAULT = 0x4001F048         # the 328-byte unreferenced cave
CODE_DSP_DEFAULT = 0x00008000      # shared RAM, DSP side (engine code)


def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        raise SystemExit("%s\n%s%s" % (" ".join(cmd), r.stdout, r.stderr))
    return r.stdout


def stock_section7(path):
    sys.path.insert(0, r"C:\Users\benan\Music\ELEKTRON\elekloader")
    from elekloader import formats
    stock, dev, rel = formats.load(path)
    return stock.section(dev.dsp_section), dev


def assemble(src, vma):
    obj = os.path.join(DSP, "engine.o")
    run([CROSS + "as", "-mcpu=54455", "-o", obj, src])
    elf = os.path.join(DSP, "engine.elf")
    binp = os.path.join(DSP, "engine.bin")
    run([CROSS + "ld", "-Ttext=0x%x" % vma, "-e", "digimachine_engine",
         "--oformat=elf32-m68k", "-o", elf, obj])
    run([CROSS + "objcopy", "-O", "binary", elf, binp])
    with open(binp, "rb") as fh:
        return fh.read()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--hook", type=lambda s: int(s, 0), default=HOOK_DEFAULT)
    ap.add_argument("--tramp", type=lambda s: int(s, 0), default=TRAMP_DEFAULT)
    ap.add_argument("--code", type=lambda s: int(s, 0), default=CODE_DSP_DEFAULT)
    ap.add_argument("--stock", default=STOCK_DEFAULT)
    ap.add_argument("--out", default=os.path.join(DSP, "digimachine.dspmod.json"))
    a = ap.parse_args()

    s7, dev = stock_section7(a.stock)
    blob = assemble(os.path.join(DSP, "engine.s"), a.code)   # linked at the DSP side
    print("engine image %d bytes (linked at 0x%08x)" % (len(blob), a.code))

    def stock_at(addr, n):
        o = addr - dev.dsp_load
        if o < 0 or o + n > len(s7):
            raise SystemExit("0x%08x is outside section 7" % addr)
        return s7[o:o + n]

    hook_stock = stock_at(a.hook, 6)
    if hook_stock[:2] != b"\x4e\xb9":
        raise SystemExit("hook 0x%08x does not hold a jsr (%s)" % (a.hook, hook_stock.hex()))
    tramp_stock = stock_at(a.tramp, 6)
    if any(tramp_stock) and a.tramp != TRAMP_DEFAULT:
        raise SystemExit("tramp 0x%08x is not zero in stock" % a.tramp)

    # the trampoline: jmp <code> then nops to fill its stock length.
    import struct
    tramp = b"\x4e\xf9" + struct.pack(">I", a.code) + b"\x4e\x71" * ((len(tramp_stock) - 6) // 2)

    import json
    doc = {
        "id": "digimachine-dsp",
        "version": "0.4",
        "title": "Digimachine Core B engine",
        "description": "Wavetable machine engine on the Digitone mk1 second CPU. "
                       "The render's voice-block jsr jumps to a cave trampoline that "
                       "jumps to the engine uploaded into shared RAM; the engine "
                       "renders the machine's 32 stereo frames into shared +0x880 and "
                       "tail-calls the displaced copy.",
        "license": "GPL-2.0-or-later",
        "device": "digitone-mk1",
        "os": "1.43",
        "sites": [
            {"addr": "0x%08x" % a.tramp, "stock": tramp_stock.hex(), "op": "bytes",
             "new": tramp.hex(), "kind": "data"},
            {"addr": "0x%08x" % a.hook, "stock": hook_stock.hex(), "op": "jsr",
             "target": "0x%08x" % a.tramp},
        ],
    }
    with open(a.out, "w") as fh:
        json.dump(doc, fh, indent=1)
        fh.write("\n")
    # also write the raw blob for the Core A uploader, and the C include the
    # Core A uploader compiles (so it can never go stale after an engine change)
    with open(os.path.join(DSP, "engine.bin"), "wb") as fh:
        fh.write(blob)
    inc = os.path.join(MOD, "engine_blob.inc")
    with open(inc, "w") as fh:
        fh.write("/* generated by build_dsp.py - the Core B engine image */\n")
        for i in range(0, len(blob), 16):
            row = blob[i:i + 16]
            fh.write("    " + ",".join("0x%02x" % b for b in row) + ",\n")
    print("wrote %s" % a.out)
    print("wrote %s" % inc)
    print("  hook jsr 0x%08x -> tramp 0x%08x -> code 0x%08x (%d bytes)"
          % (a.hook, a.tramp, a.code, len(blob)))


if __name__ == "__main__":
    main()
