"""Generate mods/digimachine/tables.inc: 8 single-cycle tables x 256 int16."""
import math
import os

N = 256
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "tables.inc")
OUT = os.path.normpath(OUT)


def norm(v):
    m = max(abs(x) for x in v) or 1.0
    return [int(round(x / m * 30000)) for x in v]


def sine():
    return [math.sin(2 * math.pi * i / N) for i in range(N)]


def tri():
    return [1 - 4 * abs(((i / N) + 0.25) % 1.0 - 0.5) for i in range(N)]


def saw():
    return [2 * (i / N) - 1 for i in range(N)]


def square():
    return [1.0 if i < N // 2 else -1.0 for i in range(N)]


def pulse25():
    return [1.0 if i < N // 4 else -1.0 for i in range(N)]


def organ():
    return [math.sin(2 * math.pi * i / N) + 0.5 * math.sin(2 * math.pi * 2 * i / N)
            + 0.25 * math.sin(2 * math.pi * 3 * i / N) for i in range(N)]


def formant():
    return [math.sin(2 * math.pi * i / N) + 0.6 * math.sin(2 * math.pi * 4 * i / N)
            + 0.3 * math.sin(2 * math.pi * 6 * i / N) for i in range(N)]


def metallic():
    s = sine()
    return [s[i] * (0.5 + 0.5 * math.sin(2 * math.pi * 7 * i / N)) for i in range(N)]


def main():
    tables = [norm(f()) for f in (sine, tri, saw, square, pulse25, organ, formant, metallic)]
    with open(OUT, "w") as fh:
        fh.write("/* generated by tools/gen_tables.py - do not edit */\n")
        for t in tables:
            for i in range(0, N, 12):
                fh.write("    " + ", ".join("%6d" % v for v in t[i:i + 12]) + ",\n")
            fh.write("\n")
    print("wrote %s" % OUT)


if __name__ == "__main__":
    main()
